"""change duration column in service to int instead of interval

Revision ID: 184b0689009a
Revises: cb2a23f34181
Create Date: 2026-02-23 17:39:38.574708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184b0689009a'
down_revision = 'cb2a23f34181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appointments_staff_id', table_name='appointments')
    op.drop_constraint('appointments_staff_id_fkey', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'staff_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('appointments_staff_id_fkey', 'appointments', 'users', ['staff_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_appointments_staff_id', 'appointments', ['staff_id'], unique=False)
    # ### end Alembic commands ###
