"""add password field

Revision ID: 2a6ec82e236f
Revises: cf3aeb169e05
Create Date: 2026-02-04 16:25:51.964693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6ec82e236f'
down_revision = 'cf3aeb169e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'password')
    # ### end Alembic commands ###
