"""add description column to permession table

Revision ID: 44d535e5366d
Revises: 2a6ec82e236f
Create Date: 2026-02-20 15:57:37.149850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d535e5366d'
down_revision = '2a6ec82e236f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permessions', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permessions', 'description')
    # ### end Alembic commands ###
