"""add indexing and staff_id to appointments and change duration to int

Revision ID: 48e56d3a53b3
Revises: 44d535e5366d
Create Date: 2026-02-20 16:41:59.833268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e56d3a53b3'
down_revision = '44d535e5366d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('staff_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_appointments_staff_id'), 'appointments', ['staff_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'users', ['staff_id'], ['id'], ondelete='RESTRICT')
    op.add_column('services', sa.Column('staff_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_services_staff_id'), 'services', ['staff_id'], unique=False)
    op.create_foreign_key(None, 'services', 'users', ['staff_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_index(op.f('ix_services_staff_id'), table_name='services')
    op.drop_column('services', 'staff_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_staff_id'), table_name='appointments')
    op.drop_column('appointments', 'staff_id')
    # ### end Alembic commands ###
