"""change column name

Revision ID: 54c50cd223f7
Revises: f543152ab4b5
Create Date: 2026-02-23 18:42:55.671864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54c50cd223f7'
down_revision = 'f543152ab4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('end_date_time', sa.DateTime(), nullable=False))
    op.drop_column('appointments', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'end_date_time')
    # ### end Alembic commands ###
