"""change default of status

Revision ID: 61175f648672
Revises: 54c50cd223f7
Create Date: 2026-02-23 19:23:19.081609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61175f648672'
down_revision = '54c50cd223f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
