"""change column name

Revision ID: f543152ab4b5
Revises: 8173c1be6468
Create Date: 2026-02-23 17:56:43.691326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f543152ab4b5'
down_revision = '8173c1be6468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('start_date_time', sa.DateTime(), nullable=False))
    op.drop_column('appointments', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('start_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'start_date_time')
    # ### end Alembic commands ###
